version: '3.7'

services:
  client:
    build: .
    image: react-app
    container_name: react-container
    volumes:
      - .:/app
    ports:
      - '8080:8080'
    stdin_open: true
    tty: true
    networks:
      - pern-app
    command: npm run client
    depends_on:
      - server
  server:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - .:/app
      - /var/nodemon.json:/nodemon.json
    container_name: node-container
    expose:
      - '3000'
    ports:
      - '3000:3000'
    command: npm run dev
    networks:
      - pern-app
networks:
  pern-app:
    driver: bridge
