version: '3.7'

services:
  ts-node:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - .:/app
      - /nodemon.json:/nodemon.json
    container_name: ts-node-container
    expose:
      - '3000'
    ports:
      - '3000:3000'
    command: npm run dev
